In [1]:
import torch
import numpy as np

In [9]:
x = torch.randn(4, 4)

In [10]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
    # test np
    a = np.ones(5)
    print(type(a))
    a.to(device)
    print(type(a))

In [13]:
device = torch.device("cpu")          # a CUDA device object
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y
print(z)
print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
# test np
a = np.ones(5)
print(type(a))
a.to(device)
print(type(a))

tensor([[ 0.8087,  0.2082,  2.2137,  1.4699],
        [ 1.8813,  0.0778,  1.8522,  1.9848],
        [ 1.5650,  1.3779,  0.7390,  0.3320],
        [ 2.8389,  0.2592,  0.9693, -0.8309]])
tensor([[ 0.8087,  0.2082,  2.2137,  1.4699],
        [ 1.8813,  0.0778,  1.8522,  1.9848],
        [ 1.5650,  1.3779,  0.7390,  0.3320],
        [ 2.8389,  0.2592,  0.9693, -0.8309]], dtype=torch.float64)
<class 'numpy.ndarray'>


AttributeError: 'numpy.ndarray' object has no attribute 'to'

In [11]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
